# Generated by Django 5.2.8 on 2025-12-10 14:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('CONTAINER', 'Container Image'), ('LIBRARY', 'Library'), ('PACKAGE', 'Package'), ('BINARY', 'Binary Executable')], default='CONTAINER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('WEB', 'Web Application'), ('REPO', 'Code Repository'), ('IMAGE', 'Docker Image'), ('ANDROID', 'Android App'), ('IOS', 'iOS App'), ('BINARY', 'Binary Executable')], default='WEB', max_length=20)),
                ('criticality', models.CharField(choices=[('CRITICAL', 'Critical (Tier 1)'), ('HIGH', 'High (Tier 2)'), ('MEDIUM', 'Medium (Tier 3)'), ('LOW', 'Low (Tier 4)')], default='MEDIUM', max_length=20)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('PRODUCT_OWNER', 'Product Owner'), ('DEVELOPER', 'Developer'), ('SERVICE_ACCOUNT', 'Service Account'), ('SECURITY_EXPERT', 'Security Expert'), ('AUDITOR', 'Auditor')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of this role's permissions")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can create, edit, and delete users')),
                ('can_manage_workspaces', models.BooleanField(default=False, help_text='Can create, edit, and delete workspaces')),
                ('can_manage_products', models.BooleanField(default=False, help_text='Can create, edit, and delete products')),
                ('can_upload_scans', models.BooleanField(default=False, help_text='Can upload scan results')),
                ('can_upload_sbom', models.BooleanField(default=False, help_text='Can upload SBOM files')),
                ('can_triage_findings', models.BooleanField(default=False, help_text='Can change vulnerability status (FP, Risk Accepted, etc.)')),
                ('can_view_all', models.BooleanField(default=False, help_text='Can view all workspaces and products')),
                ('can_export_data', models.BooleanField(default=False, help_text='Can export SBOMs and reports')),
                ('can_manage_roles', models.BooleanField(default=False, help_text='Can manage roles and permissions')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epss_url', models.URLField(default='https://epss.empiricalsecurity.com/epss_scores-current.csv.gz', help_text='URL for EPSS scores CSV (gzipped)')),
                ('kev_url', models.URLField(default='https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json', help_text='URL for CISA KEV JSON feed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('commit_hash', models.CharField(blank=True, max_length=64)),
                ('sbom_file', models.FileField(blank=True, null=True, upload_to='sboms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifacts', models.ManyToManyField(blank=True, related_name='releases', to='core.artifact')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('LIBRARY', 'Library'), ('FRAMEWORK', 'Framework'), ('CONTAINER', 'Container'), ('OS', 'Operating System')], default='LIBRARY', max_length=20)),
                ('purl', models.CharField(blank=True, max_length=300)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('license_expression', models.CharField(blank=True, help_text="License expression (e.g. 'MIT OR Apache-2.0')", max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REMOVED', 'Removed'), ('UNCHANGED', 'Unchanged')], db_index=True, default='UNCHANGED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.release')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.repository'),
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanner_name', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('findings_count', models.IntegerField(default=0)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.artifact')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.release')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash_id', models.CharField(db_index=True, editable=False, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], default='INFO', max_length=20)),
                ('finding_type', models.CharField(choices=[('SCA', 'SCA (Libraries)'), ('SECRET', 'Secret'), ('SAST', 'SAST (Code)'), ('IAC', 'IaC (Config)'), ('CONTAINER', 'Container')], default='SCA', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('line_number', models.IntegerField(default=0)),
                ('vulnerability_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('package_version', models.CharField(blank=True, max_length=100, null=True)),
                ('fix_version', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FIXED', 'Fixed'), ('WONT_FIX', 'Risk Accepted'), ('FALSE_POSITIVE', 'False Positive')], db_index=True, default='OPEN', max_length=30)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('triage_note', models.TextField(blank=True, help_text='Reason for FP or Risk Acceptance')),
                ('triage_at', models.DateTimeField(blank=True, null=True)),
                ('risk_accepted_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Expiration date for risk accepted status. If set, status will revert to OPEN after this date.', null=True)),
                ('triage_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.scan')),
            ],
            options={
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='StatusApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_status', models.CharField(choices=[('OPEN', 'Open'), ('FIXED', 'Fixed'), ('WONT_FIX', 'Risk Accepted'), ('FALSE_POSITIVE', 'False Positive')], max_length=30)),
                ('triage_note', models.TextField(blank=True, help_text='Reason for status change')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='Optional note from reviewer')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.finding')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_status_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='core.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='product',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(db_index=True, help_text="Snapshot of actor's email (preserved even if user is deleted)", max_length=255)),
                ('action', models.CharField(db_index=True, help_text='Verb describing the event (e.g., FINDING_IGNORE, USER_INVITE)', max_length=100)),
                ('resource_type', models.CharField(help_text='The model affected (e.g., Finding, Release, User)', max_length=100)),
                ('resource_id', models.CharField(help_text='ID of the target object (e.g., CVE-2024-1234, UUID)', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Diff of before/after values (e.g., {'old': 'OPEN', 'new': 'RISK_ACCEPTED'})")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Origin IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (nullable if user is deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="A descriptive name for this token (e.g., 'CI/CD Pipeline', 'Monitoring Script')", max_length=100)),
                ('token', models.CharField(db_index=True, editable=False, help_text='The actual token value (hashed)', max_length=64, unique=True)),
                ('token_preview', models.CharField(editable=False, help_text='First 8 characters of token for display', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_apitok_user_id_210ba8_idx'), models.Index(fields=['token'], name='core_apitok_token_8d7878_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['product', 'name'], name='core_releas_product_bee4b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('product', 'name')},
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['artifact', 'scanner_name', 'started_at'], name='core_scan_artifac_20f0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['status'], name='core_scan_status_604dde_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['hash_id'], name='core_findin_hash_id_94e171_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['scan', 'status'], name='core_findin_scan_id_a2d640_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status', 'severity'], name='core_findin_status_6b12c1_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['finding_type', 'status'], name='core_findin_finding_00b7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['vulnerability_id'], name='core_findin_vulnera_4ad00b_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status', 'risk_accepted_expires_at'], name='core_findin_status_8b7ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='statusapprovalrequest',
            index=models.Index(fields=['status', '-requested_at'], name='core_status_status_445c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='statusapprovalrequest',
            index=models.Index(fields=['finding', 'status'], name='core_status_finding_8c522b_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['workspace', 'name'], name='core_reposi_workspa_ee5e12_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['workspace', 'timestamp'], name='core_auditl_workspa_a5d2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_email'], name='core_auditl_actor_e_92ad56_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='core_auditl_resourc_a674ad_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['workspace', 'name', 'version'], name='core_artifa_workspa_8ce56c_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['type'], name='core_artifa_type_9b2bf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artifact',
            unique_together={('name', 'version')},
        ),
    ]
