# Generated by Django 5.2.8 on 2025-12-10 21:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams responsible for this product', related_name='products', to='core.team'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['workspace', 'name'], name='core_team_workspa_21f806_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('workspace', 'name')},
        ),
    ]
