# Generated by Django 5.2.8 on 2025-11-28 20:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('WEB', 'Web Application'), ('REPO', 'Code Repository'), ('IMAGE', 'Docker Image'), ('ANDROID', 'Android App'), ('IOS', 'iOS App'), ('BINARY', 'Binary Executable')], default='WEB', max_length=20)),
                ('criticality', models.CharField(choices=[('CRITICAL', 'Critical (Tier 1)'), ('HIGH', 'High (Tier 2)'), ('MEDIUM', 'Medium (Tier 3)'), ('LOW', 'Low (Tier 4)')], default='MEDIUM', max_length=20)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('commit_hash', models.CharField(blank=True, max_length=64)),
                ('sbom_file', models.FileField(blank=True, null=True, upload_to='sboms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='core.product')),
            ],
            options={
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('LIBRARY', 'Library'), ('FRAMEWORK', 'Framework'), ('CONTAINER', 'Container'), ('OS', 'Operating System')], default='LIBRARY', max_length=20)),
                ('purl', models.CharField(blank=True, max_length=300)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.release')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanner_name', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('findings_count', models.IntegerField(default=0)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.release')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('cve_id', models.CharField(db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('package_name', models.CharField(max_length=200)),
                ('package_version', models.CharField(max_length=100)),
                ('fixed_version', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('epss_score', models.FloatField(db_index=True, default=0.0)),
                ('epss_percentile', models.FloatField(default=0.0)),
                ('kev_status', models.BooleanField(db_index=True, default=False)),
                ('kev_date', models.DateField(blank=True, null=True)),
                ('last_enrichment', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FIXED', 'Fixed'), ('FALSE_POSITIVE', 'False Positive'), ('RISK_ACCEPTED', 'Risk Accepted'), ('DUPLICATE', 'Duplicate')], db_index=True, default='ACTIVE', max_length=20)),
                ('triage_note', models.TextField(blank=True, help_text='Reason for FP or Risk Acceptance')),
                ('triage_at', models.DateTimeField(blank=True, null=True)),
                ('hash_id', models.CharField(db_index=True, editable=False, max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('triage_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.scan')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="A descriptive name for this token (e.g., 'CI/CD Pipeline', 'Monitoring Script')", max_length=100)),
                ('token', models.CharField(db_index=True, editable=False, help_text='The actual token value (hashed)', max_length=64, unique=True)),
                ('token_preview', models.CharField(editable=False, help_text='First 8 characters of token for display', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_apitok_user_id_210ba8_idx'), models.Index(fields=['token'], name='core_apitok_token_8d7878_idx')],
            },
        ),
    ]
