# Generated by Django 5.2.8 on 2025-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REMOVED', 'Removed'), ('UNCHANGED', 'Unchanged')], db_index=True, default='UNCHANGED', max_length=20),
        ),
    ]
