# Generated by Django 5.2.8 on 2025-11-28 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_component_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('PRODUCT_OWNER', 'Product Owner'), ('DEVELOPER', 'Developer'), ('SERVICE_ACCOUNT', 'Service Account'), ('SECURITY_EXPERT', 'Security Expert'), ('AUDITOR', 'Auditor')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of this role's permissions")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can create, edit, and delete users')),
                ('can_manage_workspaces', models.BooleanField(default=False, help_text='Can create, edit, and delete workspaces')),
                ('can_manage_products', models.BooleanField(default=False, help_text='Can create, edit, and delete products')),
                ('can_upload_scans', models.BooleanField(default=False, help_text='Can upload scan results')),
                ('can_upload_sbom', models.BooleanField(default=False, help_text='Can upload SBOM files')),
                ('can_triage_findings', models.BooleanField(default=False, help_text='Can change vulnerability status (FP, Risk Accepted, etc.)')),
                ('can_view_all', models.BooleanField(default=False, help_text='Can view all workspaces and products')),
                ('can_export_data', models.BooleanField(default=False, help_text='Can export SBOMs and reports')),
                ('can_manage_roles', models.BooleanField(default=False, help_text='Can manage roles and permissions')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='core.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
