# Generated by Django 5.2.8 on 2025-12-01 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_platformsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_status', models.CharField(choices=[('ACTIVE', 'Active'), ('FIXED', 'Fixed'), ('FALSE_POSITIVE', 'False Positive'), ('RISK_ACCEPTED', 'Risk Accepted'), ('DUPLICATE', 'Duplicate')], max_length=20)),
                ('triage_note', models.TextField(blank=True, help_text='Reason for status change')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='Optional note from reviewer')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='finding',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status', 'severity'], name='finding_status_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['scan'], name='finding_scan_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status', 'epss_score'], name='finding_status_epss_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['kev_status', 'severity'], name='finding_kev_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['-created_at'], name='finding_created_at_idx'),
        ),
        migrations.AddField(
            model_name='statusapprovalrequest',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.finding'),
        ),
        migrations.AddField(
            model_name='statusapprovalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_approval_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statusapprovalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_status_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='statusapprovalrequest',
            index=models.Index(fields=['status', '-requested_at'], name='core_status_status_445c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='statusapprovalrequest',
            index=models.Index(fields=['finding', 'status'], name='core_status_finding_8c522b_idx'),
        ),
    ]
