# Generated by Django 5.2.8 on 2025-11-27 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='findings.workspace')),
            ],
        ),
    ]
