# Generated by Django 5.2.8 on 2025-11-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0003_product_created_at_product_name_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='criticality',
            field=models.CharField(choices=[('CRITICAL', 'Critical (Tier 1)'), ('HIGH', 'High (Tier 2)'), ('MEDIUM', 'Medium (Tier 3)'), ('LOW', 'Low (Tier 4)')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, default='Web', max_length=50),
        ),
    ]
