# Generated by Django 5.2.8 on 2025-11-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0004_product_criticality_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('WEB', 'Web Application'), ('REPO', 'Code Repository'), ('IMAGE', 'Docker Image'), ('ANDROID', 'Android App'), ('IOS', 'iOS App'), ('BINARY', 'Binary Executable')], default='WEB', max_length=20),
        ),
    ]
