# Generated by Django 5.2.8 on 2025-11-28 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0005_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('LIBRARY', 'Library'), ('FRAMEWORK', 'Framework'), ('CONTAINER', 'Container'), ('OS', 'Operating System')], default='LIBRARY', max_length=20)),
                ('purl', models.CharField(blank=True, max_length=300)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='findings.release')),
            ],
        ),
    ]
