# Generated by Django 5.2.8 on 2025-11-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0006_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='epss_percentile',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='finding',
            name='epss_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='finding',
            name='kev_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='kev_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finding',
            name='last_enrichment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
