# Generated by Django 5.2.8 on 2025-11-28 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0007_finding_epss_percentile_finding_epss_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='hash_id',
            field=models.CharField(db_index=True, default=1, editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FIXED', 'Fixed'), ('FALSE_POSITIVE', 'False Positive'), ('RISK_ACCEPTED', 'Risk Accepted'), ('DUPLICATE', 'Duplicate')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='triage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='triage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finding',
            name='triage_note',
            field=models.TextField(blank=True, help_text='Reason for FP or Risk Acceptance'),
        ),
    ]
